### ISSUE TITLE
`params` argument of `prepare_pacta_dashboard_data()` is never used

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.pacta.dashboard#41] opened 2024-12-05 09:36 UTC
`params` argument of `prepare_pacta_dashboard_data()` is never used

https://github.com/RMI-PACTA/workflow.pacta.dashboard/blob/d4655090be25e7754c58bb15526d91dbd4cc7b74/R/prepare_pacta_dashboard_data.R#L2

it's also commented out in the only place this function is ever called?
https://github.com/RMI-PACTA/workflow.pacta.dashboard/blob/d4655090be25e7754c58bb15526d91dbd4cc7b74/inst/extdata/scripts/prepare_dashboard_data.R#L21-L23

**Comment by AlexAxthelm** [comment] 2024-12-06 09:00
Closing as duplicate of #34

**Closed by AlexAxthelm** 2024-12-06 09:00 UTC
